name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths: [ "src/*" ]
  pull_request:
    branches: [ master ]
    paths: [ "src/*" ]

jobs:
  build:
    name: "Linux build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "true"
    - name: Install Dependencies
      run: sudo apt-get install -y cmake libgtk2.0-dev libglew-dev libglfw3-dev
    - name: cmake
      run: cmake -Dalsa=OFF ./
    - name: make
      run: make
